name: P2_RUL_Predictive_Maintenance
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - mlflow
      - fastapi
      - uvicorn
      - pydantic
      - pyyaml
