model:
  type: isolation_forest
  params:
    n_estimators: 400
    contamination: auto
data:
  window_size: 30        # minutes per rolling window
  seed: 13
train:
  test_split_ratio: 0.25
  alarm_quantile: 0.995