# P1 config
seed: 42
scan_minutes: 1
window_minutes: 30
train_minutes: 1440
val_minutes: 720
iforest:
  n_estimators: 400
  contamination: auto
alarm_budget_false_alarms_per_hour: 0.1
output_dir: artifacts
